# Generated by Django 3.1.12 on 2023-02-23 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keranjang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quintity', models.IntegerField(null=True)),
                ('subtotal', models.IntegerField(null=True)),
                ('tgl', models.DateTimeField(null=True)),
                ('no_transaksi', models.IntegerField(null=True)),
                ('bayar', models.IntegerField(null=True)),
                ('kembalian', models.CharField(max_length=50)),
                ('id_barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.barang')),
            ],
        ),
    ]
