# Generated by Django 4.1.5 on 2023-03-18 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_remove_keranjang_subtotal_alter_barang_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keranjang',
            name='kembalian',
        ),
    ]
